### PR TITLE
Add dock management via dockutil

### PR DESCRIPTION
**Pull request by enlewof**
Added dockutil install and management.  From https://blog.vandenbrand.org/2016/01/04/how-to-automate-your-mac-os-x-setup-with-ansible/

Let me know if I have to do more credits or defaults or anything.

### CODE REVIEW

**Comment by geerlingguy** [comment]
No no no, I like this :P

**Comment by geerlingguy** [comment]
This currently fails with the following error:

```
TASK [include_tasks] ***********************************************************
214
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'configure_dock' failed. The error was: error while evaluating conditional (configure_dock): 'configure_dock' is undefined\n\nThe error appears to be in '/Users/runner/work/mac-dev-playbook/mac-dev-playbook/main.yml': line 36, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - include_tasks: tasks/dock.yml\n      ^ here\n"}
```

**Comment by dspolleke** [comment]
easy fix:
in default.config.yml
configure_dock: []

I allready suggested the PR at the fork.. 
but maybe you can implement it here
https://github.com/enlewof/mac-dev-playbook/pull/2

**Comment by geerlingguy** [comment]
@enlewof - If you can add that change, it does seem like it would fix the problem. Can you do that and this could be merged?

**Comment by enlewof** [comment]
Hey thanks guys for giving me the default fix, but now it looks like I need a yaml lint fix.

```bash
Error: no-changed-when Commands should not change things if nothing needs doing
Error: no-changed-when Commands should not change things if nothing needs doing
Error: no-changed-when Commands should not change things if nothing needs doing
```
Any suggestions?

**Comment by dspolleke** [comment]
i reworked your solution in my pull request

**Comment by enlewof** [comment]
Thanks.  I'll just close this one and root for your solution to get merged.

**Pull request closed without merging**
